<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDynamicLoading>false</EnableDynamicLoading>
		<PublishTrimmed>true</PublishTrimmed>
		<PublishReadyToRun>true</PublishReadyToRun>
		<PublishReadyToRunShowWarnings>true</PublishReadyToRunShowWarnings>
		<RootNamespace>Framework.FastMath.Godot</RootNamespace>
		<AssemblyName>FastMath.Godot</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="GodotSharp" Version="4.7.0" />
		<ProjectReference Include="..\Core\FastMath.Core.csproj"
		  SetTargetFramework="TargetFramework=net8.0" />
	</ItemGroup>

</Project>
