<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>annotations</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="addons\func_godot\**" />
    <Compile Remove="addons\script-ide\**" />
    <Compile Remove="Code\Shaders\**" />
    <EmbeddedResource Remove="addons\func_godot\**" />
    <EmbeddedResource Remove="addons\script-ide\**" />
    <EmbeddedResource Remove="Code\Shaders\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Framework\Common\Common.csproj" />
    <ProjectReference Include="..\Framework\Components\Components.csproj" />
    <ProjectReference Include="..\Framework\DevConsole\Console.csproj" />
    <ProjectReference Include="..\Framework\Logger\Logger.csproj" />
    <ProjectReference Include="..\Framework\Math\Core\FastMath\FastMath.csproj" />
    <ProjectReference Include="..\Framework\Physics\Core\Physics.Integration.csproj" />
  </ItemGroup>
</Project>