<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="addons\ZenjexGodot.Generator\**" />
    <Compile Remove="Code\Model\**" />
    <EmbeddedResource Remove="addons\ZenjexGodot.Generator\**" />
    <EmbeddedResource Remove="Code\Model\**" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Code\Common\" />
    <Folder Include="Code\Gameplay\" />
    <Folder Include="Code\Components\" />
    <Folder Include="Code\Models\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FastMath\FastMath.csproj" />
  </ItemGroup>
</Project>