<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net462</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDynamicLoading>false</EnableDynamicLoading>
		<PublishReadyToRun>true</PublishReadyToRun>
		<PublishReadyToRunShowWarnings>true</PublishReadyToRunShowWarnings>
		<RootNamespace>Framework.FastMath.Core</RootNamespace>
		<AssemblyName>FastMath.Core</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="FastMath\**" />
		<EmbeddedResource Remove="FastMath\**" />
		<None Remove="FastMath\**" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net462'">
		<PackageReference Include="System.Memory" Version="4.6.3" />
		<PackageReference Include="System.Runtime" Version="4.3.1" />
	</ItemGroup>

</Project>
